variables:
  S3_BASE: https://s3.getnoc.com
  S3_BUCKET: $CI_PROJECT_NAMESPACE
  TEST: $(git describe --always --tags)

stages:
  - build
  - build_package
  - upload

build_npm:
  stage: build
  image: node:6.9-alpine
  script:
    - echo $TEST
    - apk add --update git 
    - export VERSION_FULL=$(git describe --always --tags)
    - export VERSION_SHORT=$(git describe --tags --abbrev=0 HEAD^)
    - sed -i s/"NOC BI version 0.0.0"/"NOC BI version ${VERSION_FULL}"/ index.html
    - sed -i s/0.0.0/${VERSION_SHORT}/ package.json
    - npm install
    - npm run build.prod
  tags:
    - docker
  artifacts:
    paths:
      - dist/
    expire_in: 3 min

build:
  stage: build_package
  image: python:2.7-alpine
  script:
    - apk add --update git 
    - mkdir -p dist2
    - export VERSION_SHORT=$(git describe --tags --abbrev=0 HEAD^)
    - sed -i s/0.0.0/${VERSION_SHORT}/ make.json
    - ./build.py make.json
  tags:
    - docker
  artifacts:
    paths:
      - dist2/
    expire_in: 3 min
  only:
    - tags

upload:
  stage: upload
  image: registry.getnoc.com/infrastructure/s3helper:master
  script:
    /tmp/mc -q cp dist2/* cdn/$S3_BUCKET/
  tags:
    - docker
  only:
    - tags
