stages:
  - build
  - build_package
  - upload

build_npm:
  stage: build
  image: node:7.10-alpine
  script:
    - sed -i s/0.0.0.0/${CI_BUILD_TAG}/ src/app/header/header.component.html 
    - npm install
    - npm run-script build
  tags:
    - docker
  artifacts:
    paths:
      - dist/
    expire_in: 15 min
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/


build:
  stage: build_package
  image: python:2.7-alpine
  script:
    - sed -i s/0.0.0/${CI_BUILD_TAG}/ make.json
    - ./build.py make.json
    - echo ${CI_BUILD_TAG} > dist/bi-runner.latest
  tags:
    - docker
  artifacts:
    paths:
      - dist/
    expire_in: 3 min
  only:
    - tags

upload:
  stage: upload
  image: registry.getnoc.com/infrastructure/s3helper:master
  variables:
    S3_BASE: https://s3.getnoc.com
    S3_BUCKET: $CI_PROJECT_NAMESPACE
  script:
    /tmp/mc -q cp dist/*.tar.bz2 cdn/$S3_BUCKET/
    /tmp/mc -q cp dist/*.latest cdn/$S3_BUCKET/
  tags:
    - docker
  only:
    - tags
